runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /
#   static_files: www/index.html
#   upload: www/index.html

# - url: /(.*)
#   static_files: www/\1
#   upload: www/(.*)
- url: /www
  static_dir: www

- url: /.*
  script: main.app


# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
